blank_issues_enabled: false
contact_links:
  - name: Feedback & Support
    url: https://github.com/ralflorent/namefully-python/issues
    about: |
      Please only file issues here that you believe represent actual bugs or feature
      requests for this Python library.
